### ISSUE TITLE
Feature Request: Supporting additional languages

### ISSUE THREAD

**Issue by immertroll** [yashrathi-git/headspace-cli#11]
It would be nice to support downloading different languages than English.
Maybe it could be implemented as an additional parameter.
`--language de`

It's just a variation of the header. For german <preferred language> must be "de-DE".
`headers = {
    ...
    "hs-languagepreference": "<preferred language>",
    ...
}`

Thx

**Comment by yashrathi-git** [comment]
The PR was merged in v3.1.5.

**Comment by yashrathi-git** [comment]
https://github.com/yashrathi-git/headspace-cli#changing-language-preference
