### ISSUE TITLE
Possible to download sleepcasts?

### ISSUE THREAD

**Issue by 2600box** [yashrathi-git/headspace-cli#30]
Hello, I may be missing something obvious, but it seems `sleepcasts` are in a different category? Curiously, I cannot save them for offline listening in the app.

For example, I am looking for the sleepcast `Bengal Forest`. I have this on my phone app, but I cannot find it on the desktop web site.

headspace-cli works great for everything else it seems, but is there any way for sleepcasts?

Thanks!

**Comment by yashrathi-git** [comment]
Hey, that isn't possible as that content is also not available on the web version. I reverse-engineered the requests Headspace frontend was making. To do this for an app-only feature would require lot more time.
